### ISSUE TITLE
Please Add example for Input/Output ports + Additional Stepper motor

### ISSUE THREAD

**Issue by testkid23** [dorna-robotics/dorna2-python#2]
Please Add example for Wait_for_input - to read the input ports for a specific pattern and then do something command.
Similarly, for output ports and how to use additional stepper motors.

**Comment by smhty** [comment]
We will add a document addressing the additional stepper motors.

To wait for the input, you can have a while loop, and check for a a specific input pattern that you are interested in `robot.sys`.
For example, if you are waiting for inputs 0, and 3 to turn 1, you can have something like this.

```python
# connect to the robot

# wait for input
while True:
   # first check if the keys exist 
    if all(["in0" in robot.sys, "in3" in robot.sys]):
        # check the value of the inputs for your specific pattern
        if all([robot.sys["in0"] == 1, robot.sys["in3"] == 1]):
            # Now you can exit the while loop
            break

# continue 
```
