### ISSUE TITLE
Steppers knocking and calibration lose

### ISSUE THREAD

**Issue by artemplaksiy** [dorna-robotics/dorna2-python#3]
Occasionally robot makes a knock (or several knocks) and then lose calibration. Alarm does not set during this behaviour and robot continue working with wrong position. No obstacles during the movement occurs. I'll try to make some video. Is there any other way to put additional info? Turn on debug log or something like that?

**Comment by johnjhr** [comment]
I think its hitting one of the mechanical stops maybe ?

**Comment by artemplaksiy** [comment]
@johnjaiharjose Thanks for advice, but no there was no obstacles as I wrote already. It's happens sometimes during the same movements but at random points.

**Comment by smhty** [comment]
@johnjaiharjose 
`.msg` queue, holds the last 100 messages that you have received. 
Another easy way to see the logs is to have dorna lab open and see all the logs in the log section: http://lab.dorna.ai/

Can you send us an email to support@dorna.ai and explain the issue.
Please attach any material like video if you have, and also let me know which joints lost their positions. Thanks.

**Comment by artemplaksiy** [comment]
@smhty Email just sent. Thanks
