### ISSUE TITLE
Robot lost position

### ISSUE THREAD

**Issue by allanriegel** [dorna-robotics/dorna2-python#4]
Please find below my code for the program. It usually works fine and i get on my console the following messages :
connect
moved safety position winding
moved spindle position
etc..

Knowing that i always start my cyle being already on this safety position, so the robot doesnt need to do the first movement to move to there
But sometimes, the console stays blocked after the message "connect" so the robot is not going to that position. 
In that case, i tried to kill the program, but when i restart it, the robot is going to a completely different position and bump into my other machine. 
Any idea where it could come from?

```
""
from dorna2 import dorna

robot = dorna()
ip = "169.254.58.117"
host = 443
robot.connect(ip, host)
print("conect")
for i in range(20):
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=0)
    robot.play(cmd="jmove", rel=0, id=102, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=500,accel=5000,jerk=20000)
    robot.wait(id=102, stat=2)
    print("moved safety position winding")
    robot.wait(in1=1)
    robot.play(cmd="jmove", rel=0, id=106, x=-379.45,y=11.738,z=87.78,a=1.35,b=148,vel=500,accel=5000,jerk=20000)
    robot.wait(id=106, stat=2)
    print("moved spindle position")
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.85)
    robot.play(cmd="sleep", time=1)
    print("gripper closed")
    robot.play(cmd='output',out1=1)
    print("waiting for spindle up signal")
    robot.wait(in2=1)
    print("spindle up signal received")
    robot.play(cmd="jmove", rel=0, id=107, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=1000,accel=5000,jerk=20000)
    robot.wait(id=107, stat=2)
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=1)
    print("moved safety pos")
    robot.play(cmd="jmove", rel=0, id=103, z=140,a=1.79,vel=1000,accel=5000)
    robot.wait(id=103, stat=2)
    print("moved position z high")
    robot.play(cmd="jmove", rel=0, id=104, j0=100,vel=1000,accel=10000,jerk=15000)
    robot.wait(id=104, stat=2)
    print("moved position glue")
    robot.play(cmd='output',out2=0)
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.1)
    robot.play(cmd="sleep", time=0.3)
    print("gripper opened")
    robot.play(cmd="jmove", rel=0, id=108, j0=177.8,vel=1000,accel=10000,jerk=15000)
    robot.wait(id=108, stat=2)
    print("moved position back gluing")
    robot.play(cmd="jmove", rel=0, id=109, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=1000,accel=5000,jerk=20000)
    robot.wait(id=109, stat=2)
    print("moved safety pos winding")
    print("motion", i,"is completed")

# your `code`

robot.close()
```

**Comment by smhty** [comment]
@allanriegel 
Notice that you command the robot to got to the same place at the beginning and end of your for loop.  
When you command the robot to move to a specific position while the robot has been commanded to move to that position, then the second move will not process in the robot, and you basically won't get stat 1 and stat 2 of the second move.

I recommend you put a time limit on your wait method to avoid waiting for ever or just simply remove wait for the first move in your for loop.
For example, the following code will wait for maximum 10 seconds for stat 2 of id 102.
 
``` python
    robot.play(cmd="jmove", rel=0, id=102, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=500,accel=5000,jerk=20000)
    robot.wait(time_out = 10, id=102, stat=2)
```
or ignore the `wait` because it is unnecessary.
``` python
    robot.play(cmd="jmove", rel=0, id=102, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=500,accel=5000,jerk=20000)
    # remove this wait, because it will wait forever 
    #robot.wait(id=102, stat=2)
```
I basically recommend not to send two similar motion right after each other to avoid this problem.
