### ISSUE TITLE
Execute 3 routines in different conditions with the robot.

### ISSUE THREAD

**Issue by jhonatan920** [dorna-robotics/dorna2-python#5]
Hi, I'm trying to run 2 routines that depend on 2 different digital inputs and one that runs in case the robot doesn't receive any signal.
I was trying in the following way (I attach code) but the robot does not execute any movement if it does not have a signal and if it receives the second one it does not move only when it receives the first one,
could you help me solve this problem
Regards.

[codigo robot.txt](https://github.com/dorna-robotics/dorna2-python/files/5861410/codigo.robot.txt)

**Comment by jhonatan920** [comment]
import threading

from dorna2 import dorna

robot = dorna()
ip = "169.254.168.38"
host = 443
robot.connect(ip, host)
print("conect")

while True:
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=0)
    robot.play(cmd="jmove",rel=0, id=102, j0=180, j1=180, j2=-142, j3=135,j4=0,vel=100,accel=700,jerk=3000)
    robot.play(cmd="jmove",rel=0, j0=91.42,j1=133.942,j2=-102.889,j3=0.643,j4=0,vel=100,jerk=3000,accel=700)
    robot.play(cmd="jmove",rel=0, j0=91.418,j1=33.534,j2=-112.289,j3=55.479,j4=0,vel=100,accel=700,jerk=3000)

    robot.wait(id=102, stat=2)
    print("robot waiting position")
    ##coil ready signal
    robot.wait(in1=1)
    robot.play(cmd="jmove",rel=0, id=106, j0=98.418,j1=16.838,j2=-45.357,j3=42.115,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=106, stat=2)
    print("moved position take coil")
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.85)
    robot.play(cmd="sleep", time=0.5)
    print("gripper closed")
    robot.play(cmd='output',out1=1)
    print("clamped coil signal")
    robot.wait(in2=1)
    print("z-axis signal in safe position")
    robot.play(cmd="jmove",rel=0, id=107, j0=102.946,j1=42.063,j2=-121.957,j3=93.49,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=107, stat=2)
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=1)
    print("moved safety pos")
    robot.play(cmd="jmove", rel=0, id=108, j0=-53.843,j1=42.063,j2=-121.957,j3=77.229,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=108, stat=2)
    print("moved position z high")



    if robot.wait(in4=1):
            robot.play(cmd="jmove",rel=0, id=110, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
            robot.wait(id=110, stat=2)
            robot.play(cmd="jmove", rel=0, id=111, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
            robot.wait(id=111, stat=2)
            print("moved position Red container")
    else:
            
            if robot.wait(in3=1):
                print("moved to fixture")
                robot.play(cmd="jmove", rel=0, id=112, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
                robot.wait(id=112, stat=2)
                print("moved position glue")
                robot.play(cmd='output',out2=0)
                robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.1)
                print("gripper opened")
                robot.play(cmd="jmove", rel=0, id=113, j0=-48.509,j1=19.475,j2=-55.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)               
                robot.wait(id=113, stat=2)
                print("moved position back gluing")
                robot.play(cmd="jmove",rel=0, id=114, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=114, stat=2)
                print("moved safety pos winding")



            else :

                robot.play(cmd="jmove",rel=0, id=115, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=115, stat=2)
                robot.play(cmd="jmove", rel=0, id=116, j1=100,vel=1000,accel=10000,jerk=15000)
                robot.wait(id=116, stat=2)
                print("moved position blue container")




    
robot.close()

**Comment by jhonatan920** [comment]
import threading

from dorna2 import dorna

robot = dorna()
ip = "169.254.168.38"
host = 443
robot.connect(ip, host)
print("conect")

while True:
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=0)
    robot.play(cmd="jmove",rel=0, id=102, j0=180, j1=180, j2=-142, j3=135,j4=0,vel=100,accel=700,jerk=3000)
    robot.play(cmd="jmove",rel=0, j0=91.42,j1=133.942,j2=-102.889,j3=0.643,j4=0,vel=100,jerk=3000,accel=700)
    robot.play(cmd="jmove",rel=0, j0=91.418,j1=33.534,j2=-112.289,j3=55.479,j4=0,vel=100,accel=700,jerk=3000)

    robot.wait(id=102, stat=2)
    print("robot waiting position")
    ##coil ready signal
    robot.wait(in1=1)
    robot.play(cmd="jmove",rel=0, id=106, j0=98.418,j1=16.838,j2=-45.357,j3=42.115,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=106, stat=2)
    print("moved position take coil")
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.85)
    robot.play(cmd="sleep", time=0.5)
    print("gripper closed")
    robot.play(cmd='output',out1=1)
    print("clamped coil signal")
    robot.wait(in2=1)
    print("z-axis signal in safe position")
    robot.play(cmd="jmove",rel=0, id=107, j0=102.946,j1=42.063,j2=-121.957,j3=93.49,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=107, stat=2)
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=1)
    print("moved safety pos")
    robot.play(cmd="jmove", rel=0, id=108, j0=-53.843,j1=42.063,j2=-121.957,j3=77.229,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=108, stat=2)
    print("moved position z high")



    if robot.wait(in4=1):
            robot.play(cmd="jmove",rel=0, id=110, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
            robot.wait(id=110, stat=2)
            robot.play(cmd="jmove", rel=0, id=111, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
            robot.wait(id=111, stat=2)
            print("moved position Red container")
    else:
            
            if robot.wait(in3=1):
                print("moved to fixture")
                robot.play(cmd="jmove", rel=0, id=112, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
                robot.wait(id=112, stat=2)
                print("moved position glue")
                robot.play(cmd='output',out2=0)
                robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.1)
                print("gripper opened")
                robot.play(cmd="jmove", rel=0, id=113, j0=-48.509,j1=19.475,j2=-55.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)               
                robot.wait(id=113, stat=2)
                print("moved position back gluing")
                robot.play(cmd="jmove",rel=0, id=114, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=114, stat=2)
                print("moved safety pos winding")



            else :

                robot.play(cmd="jmove",rel=0, id=115, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=115, stat=2)
                robot.play(cmd="jmove", rel=0, id=116, j1=100,vel=1000,accel=10000,jerk=15000)
                robot.wait(id=116, stat=2)
                print("moved position blue container")




    
robot.close()

**Comment by jhonatan920** [comment]
import threading
from dorna2 import dorna
robot = dorna()
ip = "169.254.168.38"
host = 443
robot.connect(ip, host)
print("conect")
while True:
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=0)
    robot.play(cmd="jmove",rel=0, id=102, j0=180, j1=180, j2=-142, j3=135,j4=0,vel=100,accel=700,jerk=3000)
    robot.play(cmd="jmove",rel=0, j0=91.42,j1=133.942,j2=-102.889,j3=0.643,j4=0,vel=100,jerk=3000,accel=700)
    robot.play(cmd="jmove",rel=0, j0=91.418,j1=33.534,j2=-112.289,j3=55.479,j4=0,vel=100,accel=700,jerk=3000)

    robot.wait(id=102, stat=2)
    print("robot waiting position")
    ##coil ready signal
    robot.wait(in1=1)
    robot.play(cmd="jmove",rel=0, id=106, j0=98.418,j1=16.838,j2=-45.357,j3=42.115,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=106, stat=2)
    print("moved position take coil")
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.85)
    robot.play(cmd="sleep", time=0.5)
    print("gripper closed")
    robot.play(cmd='output',out1=1)
    print("clamped coil signal")
    robot.wait(in2=1)
    print("z-axis signal in safe position")
    robot.play(cmd="jmove",rel=0, id=107, j0=102.946,j1=42.063,j2=-121.957,j3=93.49,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=107, stat=2)
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=1)
    print("moved safety pos")
    robot.play(cmd="jmove", rel=0, id=108, j0=-53.843,j1=42.063,j2=-121.957,j3=77.229,j4=0,vel=100,accel=700,jerk=3000)
    robot.wait(id=108, stat=2)
    print("moved position z high")



    if robot.wait(in4=1):
            robot.play(cmd="jmove",rel=0, id=110, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
            robot.wait(id=110, stat=2)
            robot.play(cmd="jmove", rel=0, id=111, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
            robot.wait(id=111, stat=2)
            print("moved position Red container")
    else:
            
            if robot.wait(in3=1):
                print("moved to fixture")
                robot.play(cmd="jmove", rel=0, id=112, j0=-52.509,j1=26.475,j2=-70.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100) 
                robot.wait(id=112, stat=2)
                print("moved position glue")
                robot.play(cmd='output',out2=0)
                robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.1)
                print("gripper opened")
                robot.play(cmd="jmove", rel=0, id=113, j0=-48.509,j1=19.475,j2=-55.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)               
                robot.wait(id=113, stat=2)
                print("moved position back gluing")
                robot.play(cmd="jmove",rel=0, id=114, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=114, stat=2)
                print("moved safety pos winding")



            else :

                robot.play(cmd="jmove",rel=0, id=115, j0=-52.509,j1=21.475,j2=-60.897,j3=-34.995,j4=0,jerk=3000,accel=700,vel=100)
                robot.wait(id=115, stat=2)
                robot.play(cmd="jmove", rel=0, id=116, j1=100,vel=1000,accel=10000,jerk=15000)
                robot.wait(id=116, stat=2)
                print("moved position blue container")




    
robot.close()

**Comment by smhty** [comment]
@jhonatan920 
I am not sure what are you trying to do in this code. However, by going over your code I figured out some mistakes and issues that probably fixes your code.

**Your code in the second post is different than `codigo robot.txt`. I only go over the `codigo robot.txt` here.** 

> Notice that if you only want to check an input value and make a decision based on that, then you can simply use `.sys` dictionary.  

> You don't need to run wait after each motion. Use `.wait` method only when it is necessary. 

> `signalglue` and `signalNG` blocks your program unless inputs 3 and 4 are both 1. I don't think that is what you want here.

> Some motions do not have any position arguments, 1d = 110and id =111.

> Notice that the two motions with id =102 and id = 109 are identical and can run  right after each other.  This can cause problem. Once the robot gets to a position, then commanding the robot to go to the same position will be ignored by the robot and you will not get the stat = 2 for the second command. So, the `wait` method will freeze your program for ever. In this case I recommend either removing one of the two motions based on your application or changing the motion parameters in one of them. Forex ample, let b= 145 for motion with id= 109

Please 
```python
import threading

from dorna2 import dorna

robot = dorna()
ip = "169.254.58.117"
host = 443
robot.connect(ip, host)
print("conect")
#signalglue = robot.wait(in3=1)
#signalNG = robot.wait(in4=1)

while true:
    robot.play(cmd='output',out1=0 , out2 = 0)
    robot.play(cmd="jmove", rel=0, id=102, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=500,accel=5000,jerk=20000)
    robot.wait(id=102, stat=2)
    print("robot waiting position")
    ##coil ready signal
    robot.wait(in1=1)
    robot.play(cmd="jmove", rel=0, id=106, x=-379.45,y=11.738,z=87.78,a=1.35,b=148,vel=500,accel=5000,jerk=20000)
    robot.wait(id=106, stat=2)
    print("moved position take coil")
    robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.85)
    robot.play(cmd="sleep", time=0.5)
    print("gripper closed")
    robot.play(cmd='output',out1=1)
    print("clamped coil signal")
    robot.wait(in2=1)
    print("z-axis signal in safe position")
    robot.play(cmd="jmove", rel=0, id=107, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=1000,accel=5000,jerk=20000)
    robot.wait(id=107, stat=2)
    robot.play(cmd='output',out1=0)
    robot.play(cmd='output',out2=1)
    print("moved safety pos")
    robot.play(cmd="jmove", rel=0, id=103, z=140,a=1.79,vel=1000,accel=5000)
    robot.wait(id=103, stat=2)
    print("moved position z high")
        if robot.sys["in3"] == 1:
                # wrong motion command format. you forgot the position
                #robot.play(cmd="jmove", rel=0, id=110, j0=100,vel=1000,accel=10000,jerk=15000)
                #robot.play(cmd="jmove", rel=0, id=111, j1=100,vel=1000,accel=10000,jerk=15000)
                #robot.wait(id=111, stat=2)
            print("moved position Red container")
        else:
            
            if robot.sys["in4"] == 1:
                robot.play(cmd="jmove", rel=0, id=104, j0=100,vel=1000,accel=10000,jerk=15000)
                robot.wait(id=104, stat=2)
                print("moved position glue")
                robot.play(cmd='output',out2=0)
                robot.play(cmd="pwm", id=10, pwm1=1, freq1=50,duty1=10.1)
                print("gripper opened")
                robot.play(cmd="jmove", rel=0, id=108, j0=177.8,vel=1000,accel=10000,jerk=15000)
                robot.play(cmd="jmove", rel=0, id=109, x=-340,y=12.361,z=95.8,a=1.78,b=148,vel=1000,accel=5000,jerk=20000)
                robot.wait(id=109, stat=2)
                print("moved safety pos winding")
            else :
                # wrong motion command format. you forgot the position
                #robot.play(cmd="jmove", rel=0, id=110, j0=100,vel=1000,accel=10000,jerk=15000)
                #robot.play(cmd="jmove", rel=0, id=111, j1=100,vel=1000,accel=10000,jerk=15000)
                #robot.wait(id=111, stat=2)
                print("moved position blue container")

robot.close()
```

**Comment by jhonatan920** [comment]
Hello I was wrong when uploading the codes, and the positions are not the real ones, it is only for testing, I wanted to see first that the conditions will work, I changed what you mentioned to me and it worked very well I attached the correct code and I wanted to know if this routine It could be put as an emergency stop, that when pressed button the robot stops.

best regards
[codigo de rutina dorna.txt](https://github.com/dorna-robotics/dorna2-python/files/5874515/codigo.de.rutina.dorna.txt)
