### ISSUE TITLE
Jmove vs lmove at J0 = 180 degrees.

### ISSUE THREAD

**Issue by johnjhr** [dorna-robotics/dorna2-python#6]
When I operate Dorna 2 at J0 = 180 degrees, Alarm is triggering because the encoder shows 180.104 in the UI. But it is not True 180.1 . Please Help. But for the same position i can use direct joint angles and not line move. I think there is a slip in encoder position when operating at 180 degrees. It jumps to 180.001 and alarm triggers due to joint limit. I tried Homing (set Joint) after turning of motors in the Home Position (hard stops and joints touching).

is it okay to use lmove  line move but give the joint angle j0 j1 j2 j3 j4. 

Also is there any problem in using Jmove and Lmove mixed in a .py script.

One Last Question, How Far can i extend the Motor Cables DB25?

**Comment by smhty** [comment]
@johnjaiharjose 

- The alarm is not sensitive to the joint value, it triggers only when there is a hard stop that prevents the joint from moving physically. So, basically you can get alarm when `j0 = 0` if there is an obstacle preventing the robot to pass `j0=0`. 
- Yes, it is OK to use both joint or cartesian coordinates for both line and joint move. However, notice that for given cartesian position you have 4 valid joint solutions. I recommend using joint for `jmove` and Cartesian coordinate for `lmove`. Also after homing and turning the motors on, first bring the robot in your start position using the `jmove` command. https://doc.dorna.ai/docs/guides/motion-concepts/
- No, there is no problem mixing the commands. In fact, the python does not care and it only sends and receives commands. 
- You should be able to extend the cables for 1 meter with a shielded DB cable. Long extension can cause noise over the encoder cables especially if the cable is not shielded.

**Comment by johnjaiharjose** [comment]
@smhty few more doubts,
is the inverse kinematics same as dorna 1 with difference only in joint length?
also, is it possible to run two connections to the robot at once. one python process for reading robot sys, and the other for executing a path.
